# Generated by Django 2.2.2 on 2019-07-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warden', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='time',
        ),
        migrations.AddField(
            model_name='student',
            name='arrival_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='departure_time',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='present_time',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='student',
            name='destination',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='vehicle',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
