# Generated by Django 2.2.2 on 2019-07-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('vehicle', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('present_time', models.TimeField(blank=True, default=None, null=True)),
                ('arrival_time', models.TimeField(blank=True, default=None, null=True)),
                ('departure_time', models.TimeField(blank=True, default=None, null=True)),
                ('full_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('permitted', models.CharField(default='False', max_length=100)),
            ],
        ),
    ]
